# Build speculos-builder and push the resulting docker image to GitHub Packages

name: Test Builder

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push test-builder to local registry
      uses: docker/build-push-action@v3
      with:
        file: build.Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: test/builder:latest
    - name: Inspect
      run: |
        docker buildx imagetools inspect test/builder:latest