# Build speculos-builder and push the resulting docker image to GitHub Packages

name: Test Builder

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5001:5001

    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push test-builder to local registry
      uses: docker/build-push-action@v3
      with:
        file: build.Dockerfile
        push: true
        tags: localhost:5001/test/builder:latest
    - name: Inspect
      run: |
        docker buildx imagetools inspect localhost:5001/test/builder:latest